#include <string.h>
#include "flatbuffers_common_reader.h"
#include "Command_reader.h" // Generated by `flatcc`.
// Convenient namespace macro to manage long namespace prefix.
#undef ns
#define ns(x) FLATBUFFERS_WRAP_NAMESPACE(AllWatchSerialize, x) // Specified in the schema.
// A helper to simplify creating vectors from C-arrays.
#define c_vec_len(V) (sizeof(V)/sizeof((V)[0]))

void setup(){
  
}
void loop(){
  
}

